-- Create table for tracking rule executions
create table if not exists automation_rule_object_executions (
  id bigint generated by default as identity primary key,
  rule_id bigint not null,
  object_id text not null,
  object_type text not null,
  user_id uuid not null, -- Supabase Auth User ID
  action_type text,
  execution_count int default 1,
  last_executed_at timestamptz default now(),
  budget_before numeric,
  budget_after numeric,
  metadata jsonb,
  created_at timestamptz default now(),
  unique(rule_id, object_id, user_id)
);

-- Enable RLS
alter table automation_rule_object_executions enable row level security;

-- Policies (Adjust as needed for security, currently permissive for internal use)
create policy "Service Role Full Access" on automation_rule_object_executions
  as permissive for all
  to service_role
  using (true)
  with check (true);
  
create policy "Users can view their own executions" on automation_rule_object_executions
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own executions" on automation_rule_object_executions
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own executions" on automation_rule_object_executions
  for update
  using (auth.uid() = user_id);
